gym_leaders = [
    {
        "name": "Sabina",
        "title": "Saffron City Gym Leader",
        "gym_number": 1,
        "type": "Psychic/Dragon",
        "greeting": "Sabina: The psychic bond between trainer and Pokémon — that is what I test here. Can your mind match mine?",
        "team": [("Ralts", 11), ("Goomy", 13), ("Kirlia", 17)],
        "reward": 1500,
    },
    {
        "name": "Whiteout",
        "title": "Goldenrod City Gym Leader",
        "gym_number": 2,
        "type": "Normal/Dragon",
        "greeting": "Whiteout: People say Normal types are plain. *smiles* I enjoy proving them wrong.",
        "team": [("Swablu", 20), ("Cyclizar", 23), ("Drampa", 26)],
        "reward": 2500,
    },
    {
        "name": "Coral",
        "title": "Slateport City Gym Leader",
        "gym_number": 3,
        "type": "Water/Dragon",
        "greeting": "Coral: I've sailed every current in this world, young one. The sea teaches patience. Let's see if you have any.",
        "team": [("Horsea", 28), ("Seadra", 32), ("Kingdra", 35)],
        "reward": 3500,
    },
    {
        "name": "Vance",
        "title": "Jubilife City Gym Leader",
        "gym_number": 4,
        "type": "Steel/Dragon",
        "greeting": "Vance: I've held this city through three sieges. Steel and Dragon — the armour and the cause. Show me you're worth fighting beside.",
        "team": [("Steelbit", 37), ("Doublade", 40), ("Ironmaw", 44)],
        "reward": 4500,
    },
    {
        "name": "Rook",
        "title": "Castelia City Gym Leader",
        "gym_number": 5,
        "type": "Dark/Dragon",
        "greeting": "Rook: You made it to the top floor. Not bad. Means you know how to climb. Let's see if you know how to fight.",
        "team": [("Houndoom", 44), ("Krokorok", 46), ("Zoroark", 48), ("Roaring Moon", 51)],
        "reward": 5500,
    },
    {
        "name": "Lysara",
        "title": "Lumiose City Gym Leader",
        "gym_number": 6,
        "type": "Fire/Dragon",
        "greeting": "Lysara: In this city, light is everything. I will burn away every shadow you bring into this gym.",
        "team": [("Turtonator", 52), ("Chandelure", 55), ("Serfyre", 58)],
        "reward": 6500,
    },
    {
        "name": "Tide",
        "title": "Hau'oli City Gym Leader",
        "gym_number": 7,
        "type": "Flying/Dragon",
        "greeting": "Tide: *barefoot, mid-stretch* Oh hey. Figured you'd show up. Wanna battle? Should be fun.",
        "team": [("Altaria", 59), ("Noivern", 62), ("Corviknight", 64), ("Dragonite", 67)],
        "reward": 7500,
    },
    {
        "name": "Flint",
        "title": "Hammerlocke Gym Leader",
        "gym_number": 8,
        "type": "Rock/Dragon",
        "greeting": "Flint: An old knight's code — you meet your opponent head-on. No tricks. Just strength. COME ON!",
        "team": [("Rampardos", 65), ("Gigalith", 67), ("Tyranitar", 70), ("Tyrantrum", 73)],
        "reward": 8500,
    },
    {
        "name": "Dad",
        "title": "Bakil City Gym Leader",
        "gym_number": 9,
        "type": "Ground/Dragon",
        "greeting": "Dad: *smiles* You've grown so much, NH. I'm proud of you. Now show me everything you've learned.",
        "team": [("Vibrava", 74), ("Gliscor", 76), ("Krookodile", 78), ("Flygon", 81), ("Garchomp", 84)],
        "reward": 10000,
    },
]
