learnsets = {
    # Custom Draconia Pokemon
    "Frodger": {
        1: ["Scratch"],
        5: ["Ember"],
        8: ["Metal Claw"],
        12: ["Flame Charge"],
        20: ["Flamethrower"],
        35: ["Fire Blast"],
    },
    "Frogandi": {
        1: ["Ember"],
        5: ["Dragon Rage"],
        10: ["Flame Charge"],
        20: ["Flamethrower"],
        35: ["Fire Blast"],
    },
    "Frogainian": {
        1: ["Dragon Rage"],
        5: ["Flame Charge"],
        10: ["Twister"],
        20: ["Iron Head"],
        30: ["Flamethrower"],
        45: ["Fire Blast"],
    },
    "Buliz": {
        1: ["Scratch"],
        5: ["Bubble"],
        8: ["Water Gun"],
        12: ["Karate Chop"],
        20: ["Surf"],
        35: ["Hydro Pump"],
    },
    "Bulits": {
        1: ["Bubble"],
        5: ["Water Gun"],
        10: ["Karate Chop"],
        20: ["Surf"],
        35: ["Hydro Pump"],
    },
    "Bulitzer": {
        1: ["Water Gun"],
        5: ["Karate Chop"],
        10: ["Surf"],
        20: ["Close Combat"],
        35: ["Hydro Pump"],
    },
    "Falake": {
        1: ["Scratch", "Dragon Rage"],
        5: ["Leafage"],
        8: ["Razor Leaf"],
        12: ["Confusion"],
        20: ["Giga Drain"],
        35: ["Solar Beam"],
    },
    "Faelke": {
        1: ["Leafage"],
        5: ["Razor Leaf"],
        10: ["Confusion"],
        20: ["Giga Drain"],
        35: ["Solar Beam"],
    },
    "Psyake": {
        1: ["Razor Leaf"],
        5: ["Confusion"],
        10: ["Giga Drain"],
        20: ["Psybeam"],
        30: ["Psychic"],
        45: ["Solar Beam"],
    },
    "Roggenrola": {
        1: ["Scratch"],
        4: ["Rock Throw"],
        8: ["Rock Blast"],
        15: ["Rock Slide"],
        30: ["Stone Edge"],
    },
    "Boldore": {
        1: ["Rock Throw"],
        5: ["Rock Blast"],
        10: ["Rock Slide"],
        25: ["Stone Edge"],
    },
    "Gigalith": {
        1: ["Rock Blast"],
        5: ["Rock Slide"],
        10: ["Stone Edge"],
        25: ["Earthquake"],
    },
    "Dratini": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        8: ["Twister"],
        20: ["Dragon Pulse"],
        35: ["Outrage"],
    },
    "Dragonair": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Dragon Pulse"],
        25: ["Outrage"],
        40: ["Draco Meteor"],
    },
    "Dragonite": {
        1: ["Dragon Rage"],
        5: ["Dragon Pulse"],
        10: ["Outrage"],
        20: ["Hurricane"],
        40: ["Draco Meteor"],
    },
    "Flamlet": {
        1: ["Scratch"],
        4: ["Ember"],
        8: ["Dragon Rage"],
        15: ["Flamethrower"],
        25: ["Dragon Pulse"],
        40: ["Fire Blast"],
    },
    "Serfling": {
        1: ["Ember"],
        5: ["Dragon Rage"],
        10: ["Flame Charge"],
        20: ["Flamethrower"],
        35: ["Dragon Pulse"],
    },
    "Serfyre": {
        1: ["Dragon Rage"],
        5: ["Flame Charge"],
        10: ["Twister"],
        20: ["Flamethrower"],
        35: ["Dragon Pulse"],
        50: ["Fire Blast"],
    },
    "Frostlet": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Ice Shard"],
        20: ["Ice Beam"],
        35: ["Blizzard"],
    },
    "Glacilet": {
        1: ["Dragon Rage"],
        6: ["Metal Claw"],
        15: ["Ice Shard"],
        25: ["Ice Beam"],
        40: ["Blizzard"],
    },
    "Glaciwyrm": {
        1: ["Dragon Rage"],
        5: ["Metal Claw"],
        10: ["Twister"],
        20: ["Ice Beam"],
        35: ["Blizzard"],
    },
    "Riplet": {
        1: ["Scratch"],
        4: ["Bubble"],
        8: ["Water Gun"],
        15: ["Surf"],
        30: ["Hydro Pump"],
    },
    "Aqualet": {
        1: ["Bubble"],
        5: ["Water Gun"],
        10: ["Surf"],
        25: ["Hydro Pump"],
    },
    "Aqualisk": {
        1: ["Water Gun"],
        5: ["Surf"],
        10: ["Twister"],
        20: ["Hydro Pump"],
        35: ["Dragon Pulse"],
    },
    "Sparklet": {
        1: ["Scratch"],
        4: ["Thunder Shock"],
        8: ["Dragon Rage"],
        15: ["Thunderbolt"],
        30: ["Thunder"],
    },
    "Voltlet": {
        1: ["Thunder Shock"],
        5: ["Dragon Rage"],
        10: ["Thunderbolt"],
        25: ["Twister"],
        40: ["Thunder"],
    },
    "Voltscale": {
        1: ["Thunder Shock"],
        5: ["Thunderbolt"],
        10: ["Dragon Rage"],
        25: ["Thunder"],
        40: ["Twister"],
    },
    "Ironlet": {
        1: ["Scratch"],
        4: ["Metal Claw"],
        8: ["Dragon Rage"],
        20: ["Iron Head"],
        35: ["Flash Cannon"],
    },
    "Steelbit": {
        1: ["Metal Claw"],
        5: ["Dragon Rage"],
        10: ["Iron Head"],
        25: ["Flash Cannon"],
    },
    "Ironmaw": {
        1: ["Metal Claw"],
        5: ["Dragon Rage"],
        10: ["Iron Head"],
        20: ["Flash Cannon"],
        35: ["Outrage"],
    },
    "Misting": {
        1: ["Scratch"],
        5: ["Confusion"],
        9: ["Dragon Rage"],
        20: ["Shadow Ball"],
        35: ["Phantom Force"],
    },
    "Phantling": {
        1: ["Confusion"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        20: ["Shadow Ball"],
        35: ["Dragon Pulse"],
    },
    "Phantail": {
        1: ["Dragon Rage"],
        5: ["Confusion"],
        10: ["Twister"],
        20: ["Shadow Ball"],
        30: ["Phantom Force"],
        45: ["Draco Meteor"],
    },
    "Quadrabirr": {
        1: ["Scratch"],
        4: ["Thunder Shock"],
        8: ["Gust"],
        15: ["Thunderbolt"],
        25: ["Air Slash"],
        40: ["Thunder"],
    },
    "Dinovinery": {
        1: ["Leafage"],
        5: ["Razor Leaf"],
        10: ["Sludge"],
        20: ["Giga Drain"],
        35: ["Solar Beam"],
    },
    "Draponie": {
        1: ["Confusion"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        20: ["Dragon Pulse"],
        35: ["Draco Meteor"],
    },
    "Prototype": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Bite"],
        20: ["Crunch"],
        30: ["Dark Pulse"],
        45: ["Draco Meteor"],
    },
    "Debuner": {
        1: ["Scratch"],
        5: ["Bulldoze"],
        10: ["Sludge"],
        20: ["Earthquake"],
        35: ["Sludge Bomb"],
    },
    "Rasnail": {
        1: ["Scratch"],
        4: ["Rock Throw"],
        8: ["Bug Bite"],
        15: ["Rock Slide"],
        25: ["X-Scissor"],
        35: ["Stone Edge"],
    },
    "Pecharunt": {
        1: ["Shadow Sneak"],
        5: ["Sludge"],
        10: ["Shadow Ball"],
        20: ["Sludge Bomb"],
        35: ["Phantom Force"],
    },
    "Zygarde-10": {
        1: ["Scratch"],
        4: ["Dragon Rage"],
        8: ["Bulldoze"],
        15: ["Earthquake"],
        25: ["Dragon Pulse"],
        40: ["Outrage"],
    },
    "Zygarde-50": {
        1: ["Dragon Rage"],
        5: ["Bulldoze"],
        10: ["Earthquake"],
        20: ["Dragon Pulse"],
        35: ["Outrage"],
    },
    "Zygarde-Complete": {
        1: ["Dragon Rage"],
        5: ["Earthquake"],
        10: ["Dragon Pulse"],
        20: ["Outrage"],
        35: ["Draco Meteor"],
    },
    # Gen 2
    "Horsea": {
        1: ["Scratch"],
        4: ["Bubble"],
        8: ["Water Gun"],
        15: ["Surf"],
        25: ["Dragon Pulse"],
        40: ["Hydro Pump"],
    },
    "Seadra": {
        1: ["Bubble"],
        5: ["Water Gun"],
        10: ["Dragon Rage"],
        18: ["Surf"],
        28: ["Dragon Pulse"],
        40: ["Hydro Pump"],
    },
    "Charmander": {
        1: ["Scratch"],
        5: ["Ember"],
        12: ["Flame Charge"],
        20: ["Flamethrower"],
        36: ["Fire Blast"],
    },
    "Charmeleon": {
        1: ["Ember"],
        5: ["Flame Charge"],
        20: ["Flamethrower"],
        36: ["Fire Blast"],
    },
    "Charizard": {
        1: ["Flamethrower"],
        5: ["Air Slash"],
        20: ["Fire Blast"],
        36: ["Dragon Pulse"],
        50: ["Outrage"],
    },
    "Kingdra": {
        1: ["Water Gun"],
        5: ["Dragon Rage"],
        10: ["Surf"],
        20: ["Dragon Pulse"],
        35: ["Hydro Pump"],
        50: ["Draco Meteor"],
    },
    # Gen 3
    "Bagon": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        20: ["Dragon Pulse"],
        35: ["Outrage"],
    },
    "Shelgon": {
        1: ["Dragon Rage"],
        5: ["Metal Claw"],
        10: ["Twister"],
        20: ["Dragon Pulse"],
        35: ["Outrage"],
    },
    "Salamence": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Metal Claw"],
        20: ["Dragon Pulse"],
        30: ["Hurricane"],
        45: ["Outrage"],
        55: ["Draco Meteor"],
    },
    "Swablu": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Gust"],
        20: ["Air Slash"],
    },
    "Altaria": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Confusion"],
        20: ["Air Slash"],
        30: ["Dragon Pulse"],
        45: ["Hurricane"],
    },
    "Trapinch": {
        1: ["Scratch"],
        4: ["Rock Throw"],
        8: ["Rock Blast"],
        12: ["Dragon Rage"],
        20: ["Bulldoze"],
        32: ["Earthquake"],
    },
    "Vibrava": {
        1: ["Dragon Rage"],
        5: ["Rock Throw"],
        10: ["Twister"],
        20: ["Bulldoze"],
        30: ["Dragon Pulse"],
        42: ["Earthquake"],
    },
    "Flygon": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Rock Blast"],
        20: ["Dragon Pulse"],
        30: ["Earthquake"],
        50: ["Outrage"],
    },
    "Latias": {
        1: ["Confusion"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        20: ["Psybeam"],
        30: ["Dragon Pulse"],
        40: ["Psychic"],
        55: ["Draco Meteor"],
    },
    "Latios": {
        1: ["Confusion"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        20: ["Psybeam"],
        30: ["Dragon Pulse"],
        40: ["Psychic"],
        55: ["Draco Meteor"],
    },
    "Rayquaza": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Metal Claw"],
        20: ["Dragon Pulse"],
        30: ["Air Slash"],
        40: ["Outrage"],
        50: ["Hurricane"],
        65: ["Draco Meteor"],
    },
    # Gen 4
    "Gible": {
        1: ["Scratch"],
        4: ["Dragon Rage"],
        8: ["Rock Throw"],
        12: ["Twister"],
        22: ["Bulldoze"],
        32: ["Dragon Pulse"],
    },
    "Gabite": {
        1: ["Dragon Rage"],
        5: ["Rock Throw"],
        10: ["Twister"],
        20: ["Dragon Pulse"],
        32: ["Earthquake"],
        45: ["Outrage"],
    },
    "Garchomp": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Rock Blast"],
        20: ["Dragon Pulse"],
        30: ["Earthquake"],
        42: ["Outrage"],
        55: ["Draco Meteor"],
    },
    "Dialga": {
        1: ["Metal Claw"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        20: ["Iron Head"],
        30: ["Dragon Pulse"],
        42: ["Flash Cannon"],
        55: ["Draco Meteor"],
    },
    "Palkia": {
        1: ["Water Gun"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        20: ["Surf"],
        30: ["Dragon Pulse"],
        42: ["Hydro Pump"],
        55: ["Draco Meteor"],
    },
    "Giratina": {
        1: ["Dragon Rage"],
        5: ["Confusion"],
        10: ["Twister"],
        20: ["Shadow Ball"],
        30: ["Dragon Pulse"],
        42: ["Phantom Force"],
        55: ["Draco Meteor"],
    },
    # Gen 5
    "Axew": {
        1: ["Scratch"],
        4: ["Dragon Rage"],
        8: ["Metal Claw"],
        12: ["Twister"],
        22: ["Dragon Pulse"],
        38: ["Outrage"],
    },
    "Fraxure": {
        1: ["Dragon Rage"],
        5: ["Metal Claw"],
        10: ["Twister"],
        20: ["Dragon Pulse"],
        38: ["Outrage"],
    },
    "Haxorus": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Metal Claw"],
        20: ["Dragon Pulse"],
        38: ["Outrage"],
        55: ["Draco Meteor"],
    },
    "Deino": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        18: ["Bite"],
        28: ["Dragon Pulse"],
        40: ["Crunch"],
    },
    "Zweilous": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Confusion"],
        20: ["Bite"],
        30: ["Dragon Pulse"],
        42: ["Dark Pulse"],
    },
    "Hydreigon": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Confusion"],
        20: ["Dark Pulse"],
        30: ["Dragon Pulse"],
        42: ["Crunch"],
        55: ["Draco Meteor"],
    },
    "Druddigon": {
        1: ["Scratch"],
        4: ["Dragon Rage"],
        8: ["Metal Claw"],
        12: ["Rock Throw"],
        22: ["Dragon Pulse"],
        35: ["Outrage"],
    },
    "Reshiram": {
        1: ["Ember"],
        5: ["Dragon Rage"],
        10: ["Flame Charge"],
        18: ["Twister"],
        28: ["Flamethrower"],
        38: ["Dragon Pulse"],
        50: ["Fire Blast"],
        62: ["Draco Meteor"],
    },
    "Zekrom": {
        1: ["Dragon Rage"],
        5: ["Metal Claw"],
        10: ["Twister"],
        20: ["Thunder Shock"],
        30: ["Dragon Pulse"],
        42: ["Thunderbolt"],
        55: ["Thunder"],
        65: ["Draco Meteor"],
    },
    "Kyurem": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Metal Claw"],
        20: ["Ice Shard"],
        30: ["Dragon Pulse"],
        42: ["Ice Beam"],
        55: ["Blizzard"],
        65: ["Draco Meteor"],
    },
    # Gen 6
    "Goomy": {
        1: ["Scratch"],
        4: ["Bubble"],
        8: ["Dragon Rage"],
        18: ["Sludge"],
        28: ["Dragon Pulse"],
    },
    "Sliggoo": {
        1: ["Bubble"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        22: ["Sludge"],
        32: ["Dragon Pulse"],
        45: ["Hydro Pump"],
    },
    "Goodra": {
        1: ["Dragon Rage"],
        5: ["Water Gun"],
        10: ["Twister"],
        20: ["Dragon Pulse"],
        32: ["Sludge Bomb"],
        45: ["Hydro Pump"],
        58: ["Draco Meteor"],
    },
    "Noibat": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        8: ["Confusion"],
        18: ["Gust"],
        28: ["Air Slash"],
    },
    "Noivern": {
        1: ["Dragon Rage"],
        5: ["Confusion"],
        10: ["Twister"],
        20: ["Air Slash"],
        30: ["Dragon Pulse"],
        42: ["Hurricane"],
        55: ["Draco Meteor"],
    },
    "Tyrunt": {
        1: ["Scratch"],
        4: ["Rock Throw"],
        8: ["Dragon Rage"],
        12: ["Rock Blast"],
        22: ["Rock Slide"],
        32: ["Crunch"],
        42: ["Stone Edge"],
    },
    "Tyrantrum": {
        1: ["Rock Throw"],
        5: ["Dragon Rage"],
        10: ["Rock Blast"],
        18: ["Twister"],
        28: ["Rock Slide"],
        38: ["Crunch"],
        48: ["Stone Edge"],
        58: ["Outrage"],
    },
    # Gen 7
    "Jangmo-o": {
        1: ["Scratch"],
        4: ["Dragon Rage"],
        8: ["Metal Claw"],
        18: ["Karate Chop"],
        28: ["Dragon Pulse"],
    },
    "Hakamo-o": {
        1: ["Dragon Rage"],
        5: ["Karate Chop"],
        10: ["Metal Claw"],
        22: ["Close Combat"],
        35: ["Dragon Pulse"],
    },
    "Kommo-o": {
        1: ["Dragon Rage"],
        5: ["Karate Chop"],
        10: ["Twister"],
        18: ["Metal Claw"],
        28: ["Close Combat"],
        38: ["Dragon Pulse"],
        50: ["Outrage"],
        62: ["Draco Meteor"],
    },
    "Drampa": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Confusion"],
        22: ["Dragon Pulse"],
        35: ["Psybeam"],
        48: ["Outrage"],
    },
    "Turtonator": {
        1: ["Ember"],
        5: ["Dragon Rage"],
        10: ["Flame Charge"],
        18: ["Twister"],
        28: ["Flamethrower"],
        40: ["Dragon Pulse"],
        52: ["Fire Blast"],
    },
    "Applin": {
        1: ["Scratch"],
        4: ["Leafage"],
        8: ["Dragon Rage"],
        18: ["Razor Leaf"],
        28: ["Dragon Pulse"],
    },
    "Flapple": {
        1: ["Leafage"],
        5: ["Dragon Rage"],
        10: ["Razor Leaf"],
        18: ["Twister"],
        28: ["Giga Drain"],
        38: ["Dragon Pulse"],
        50: ["Solar Beam"],
    },
    # Gen 8
    "Dreepy": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Shadow Sneak"],
    },
    "Drakloak": {
        1: ["Dragon Rage"],
        5: ["Confusion"],
        10: ["Twister"],
        22: ["Shadow Ball"],
        35: ["Dragon Pulse"],
    },
    "Dragapult": {
        1: ["Dragon Rage"],
        5: ["Confusion"],
        10: ["Twister"],
        18: ["Metal Claw"],
        28: ["Shadow Ball"],
        38: ["Dragon Pulse"],
        50: ["Phantom Force"],
        62: ["Draco Meteor"],
    },
    "Duraludon": {
        1: ["Metal Claw"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        22: ["Iron Head"],
        32: ["Flash Cannon"],
        45: ["Dragon Pulse"],
        58: ["Draco Meteor"],
    },
    # Gen 9
    "Frigibax": {
        1: ["Scratch"],
        4: ["Dragon Rage"],
        8: ["Metal Claw"],
        18: ["Ice Shard"],
        28: ["Dragon Pulse"],
    },
    "Arctibax": {
        1: ["Dragon Rage"],
        5: ["Metal Claw"],
        10: ["Twister"],
        22: ["Ice Beam"],
        35: ["Dragon Pulse"],
    },
    "Baxcalibur": {
        1: ["Dragon Rage"],
        5: ["Twister"],
        10: ["Metal Claw"],
        20: ["Ice Beam"],
        32: ["Dragon Pulse"],
        44: ["Blizzard"],
        56: ["Outrage"],
    },
    "Cyclizar": {
        1: ["Scratch"],
        5: ["Dragon Rage"],
        10: ["Twister"],
        22: ["Dragon Pulse"],
        38: ["Outrage"],
    },
    "Tatsugiri": {
        1: ["Bubble"],
        5: ["Water Gun"],
        10: ["Dragon Rage"],
        18: ["Twister"],
        28: ["Surf"],
        38: ["Dragon Pulse"],
        50: ["Hydro Pump"],
    },
    # Team Fairy Pokemon
    "Clefairy": {
        1: ["Scratch"],
        5: ["Dazzling Gleam"],
        14: ["Moonblast"],
    },
    "Clefable": {
        1: ["Dazzling Gleam"],
        5: ["Moonblast"],
        15: ["Psychic"],
    },
    "Snubbull": {
        1: ["Scratch"],
        5: ["Play Rough"],
        14: ["Moonblast"],
    },
    "Granbull": {
        1: ["Play Rough"],
        5: ["Moonblast"],
        15: ["Close Combat"],
    },
    "Sylveon": {
        1: ["Dazzling Gleam"],
        5: ["Moonblast"],
        15: ["Shadow Ball"],
        28: ["Psychic"],
    },
    "Mimikyu": {
        1: ["Shadow Sneak"],
        5: ["Play Rough"],
        12: ["Shadow Ball"],
        22: ["Phantom Force"],
    },
    "Togekiss": {
        1: ["Dazzling Gleam"],
        5: ["Air Slash"],
        12: ["Moonblast"],
        25: ["Hurricane"],
    },
    "Gardevoir": {
        1: ["Confusion"],
        5: ["Dazzling Gleam"],
        12: ["Psychic"],
        22: ["Moonblast"],
        35: ["Shadow Ball"],
    },
    "Xerneas": {
        1: ["Moonblast"],
        5: ["Dazzling Gleam"],
        10: ["Play Rough"],
        20: ["Psychic"],
        35: ["Close Combat"],
    },
    # Gen 1 additions
    "Gastly": {
        1: ["Shadow Sneak"],
        5: ["Confusion"],
        12: ["Sludge"],
        20: ["Shadow Ball"],
    },
    "Haunter": {
        1: ["Shadow Sneak"],
        5: ["Sludge"],
        12: ["Shadow Ball"],
        22: ["Dark Pulse"],
        32: ["Psychic"],
    },
    "Gengar": {
        1: ["Shadow Ball"],
        5: ["Dark Pulse"],
        12: ["Sludge Bomb"],
        22: ["Psychic"],
        35: ["Phantom Force"],
    },
    "Onix": {
        1: ["Rock Throw"],
        5: ["Scratch"],
        12: ["Rock Blast"],
        22: ["Bulldoze"],
        32: ["Body Slam"],
    },
    "Steelix": {
        1: ["Iron Head"],
        5: ["Rock Slide"],
        12: ["Earthquake"],
        22: ["Flash Cannon"],
        35: ["Stone Edge"],
    },
    "Magikarp": {
        1: ["Scratch"],
    },
    "Gyarados": {
        1: ["Water Gun"],
        5: ["Bite"],
        12: ["Crunch"],
        20: ["Surf"],
        30: ["Dark Pulse"],
        45: ["Hydro Pump"],
    },
    "Scyther": {
        1: ["Scratch"],
        5: ["Bug Bite"],
        12: ["Air Slash"],
        20: ["X-Scissor"],
        30: ["Close Combat"],
    },
    "Scizor": {
        1: ["Metal Claw"],
        5: ["Bug Bite"],
        12: ["X-Scissor"],
        20: ["Iron Head"],
        30: ["Close Combat"],
        42: ["Flash Cannon"],
    },
    # Gen 4 additions
    "Cranidos": {
        1: ["Scratch"],
        5: ["Rock Throw"],
        12: ["Rock Blast"],
        20: ["Body Slam"],
        28: ["Rock Slide"],
    },
    "Rampardos": {
        1: ["Rock Slide"],
        5: ["Body Slam"],
        12: ["Stone Edge"],
        22: ["Earthquake"],
        35: ["Close Combat"],
    },
    "Honedge": {
        1: ["Metal Claw"],
        5: ["Shadow Sneak"],
        14: ["Iron Head"],
    },
    "Doublade": {
        1: ["Iron Head"],
        5: ["Shadow Ball"],
        14: ["Flash Cannon"],
        25: ["Close Combat"],
    },
    "Aegislash": {
        1: ["Iron Head"],
        5: ["Shadow Ball"],
        12: ["Flash Cannon"],
        22: ["Phantom Force"],
        35: ["Close Combat"],
    },
    "Rookidee": {
        1: ["Scratch"],
        5: ["Gust"],
        12: ["Air Slash"],
    },
    "Corvisquire": {
        1: ["Gust"],
        5: ["Air Slash"],
        12: ["Crunch"],
        22: ["Body Slam"],
    },
    "Corviknight": {
        1: ["Air Slash"],
        5: ["Iron Head"],
        12: ["Flash Cannon"],
        22: ["Hurricane"],
        35: ["Body Slam"],
    },
    # Gen 2 additions
    "Misdreavus": {
        1: ["Shadow Sneak"],
        5: ["Confusion"],
        12: ["Psybeam"],
        20: ["Shadow Ball"],
    },
    "Mismagius": {
        1: ["Shadow Ball"],
        5: ["Psychic"],
        12: ["Dark Pulse"],
        25: ["Phantom Force"],
    },
    "Sneasel": {
        1: ["Scratch"],
        5: ["Ice Shard"],
        10: ["Bite"],
        20: ["Crunch"],
        30: ["Dark Pulse"],
    },
    "Weavile": {
        1: ["Ice Shard"],
        5: ["Crunch"],
        12: ["X-Scissor"],
        20: ["Dark Pulse"],
        35: ["Ice Beam"],
    },
    "Houndour": {
        1: ["Ember"],
        5: ["Bite"],
        12: ["Flame Charge"],
        20: ["Crunch"],
    },
    "Houndoom": {
        1: ["Crunch"],
        5: ["Flamethrower"],
        12: ["Dark Pulse"],
        25: ["Fire Blast"],
        38: ["Sludge Bomb"],
    },
    "Gligar": {
        1: ["Scratch"],
        5: ["Bulldoze"],
        12: ["X-Scissor"],
        22: ["Air Slash"],
    },
    "Gliscor": {
        1: ["X-Scissor"],
        5: ["Earthquake"],
        12: ["Air Slash"],
        22: ["Stone Edge"],
        35: ["Dark Pulse"],
    },
    "Larvitar": {
        1: ["Scratch"],
        5: ["Rock Throw"],
        10: ["Bite"],
        18: ["Bulldoze"],
    },
    "Pupitar": {
        1: ["Rock Blast"],
        5: ["Crunch"],
        12: ["Bulldoze"],
        22: ["Rock Slide"],
    },
    "Tyranitar": {
        1: ["Crunch"],
        5: ["Rock Slide"],
        12: ["Earthquake"],
        20: ["Dark Pulse"],
        30: ["Stone Edge"],
        45: ["Outrage"],
    },
    # Gen 5 additions
    "Zorua": {
        1: ["Scratch"],
        5: ["Bite"],
        12: ["Dark Pulse"],
        22: ["Shadow Ball"],
    },
    "Zoroark": {
        1: ["Dark Pulse"],
        5: ["Shadow Ball"],
        12: ["Crunch"],
        22: ["Close Combat"],
        35: ["Flamethrower"],
    },
    "Sandile": {
        1: ["Scratch"],
        5: ["Bite"],
        12: ["Bulldoze"],
        20: ["Rock Throw"],
    },
    "Krokorok": {
        1: ["Crunch"],
        5: ["Bulldoze"],
        12: ["Rock Slide"],
        22: ["Dark Pulse"],
    },
    "Krookodile": {
        1: ["Crunch"],
        5: ["Earthquake"],
        12: ["Dark Pulse"],
        22: ["Stone Edge"],
        35: ["Outrage"],
    },
    "Pawniard": {
        1: ["Metal Claw"],
        5: ["Bite"],
        12: ["Iron Head"],
        20: ["Crunch"],
    },
    "Bisharp": {
        1: ["Iron Head"],
        5: ["Crunch"],
        12: ["Dark Pulse"],
        22: ["Flash Cannon"],
        35: ["Stone Edge"],
    },
    "Kingambit": {
        1: ["Iron Head"],
        5: ["Dark Pulse"],
        12: ["Close Combat"],
        22: ["Stone Edge"],
        35: ["Crunch"],
    },
    "Litwick": {
        1: ["Ember"],
        5: ["Shadow Sneak"],
        12: ["Confusion"],
        20: ["Flame Charge"],
    },
    "Lampent": {
        1: ["Shadow Ball"],
        5: ["Flamethrower"],
        12: ["Confusion"],
        22: ["Dark Pulse"],
    },
    "Chandelure": {
        1: ["Shadow Ball"],
        5: ["Flamethrower"],
        12: ["Fire Blast"],
        22: ["Dark Pulse"],
        35: ["Phantom Force"],
    },
    # Gen 7 additions
    "Salandit": {
        1: ["Scratch"],
        5: ["Ember"],
        12: ["Sludge"],
        20: ["Flame Charge"],
    },
    "Salazzle": {
        1: ["Flamethrower"],
        5: ["Sludge Bomb"],
        12: ["Dark Pulse"],
        25: ["Fire Blast"],
    },
    # Gen 8 additions
    "Toxel": {
        1: ["Thunder Shock"],
        5: ["Scratch"],
        12: ["Sludge"],
    },
    "Toxtricity": {
        1: ["Thunderbolt"],
        5: ["Sludge Bomb"],
        12: ["Dark Pulse"],
        25: ["Thunder"],
    },
    # Gen 9 additions
    "Roaring Moon": {
        1: ["Dragon Pulse"],
        5: ["Crunch"],
        12: ["Dark Pulse"],
        22: ["Outrage"],
        35: ["Close Combat"],
        50: ["Draco Meteor"],
    },
    "Walking Wake": {
        1: ["Dragon Pulse"],
        5: ["Surf"],
        12: ["Hydro Pump"],
        22: ["Outrage"],
        35: ["Draco Meteor"],
    },
    # Gen 3 additions
    "Aron": {
        1: ["Metal Claw"],
        5: ["Rock Throw"],
        14: ["Iron Head"],
    },
    "Lairon": {
        1: ["Iron Head"],
        5: ["Rock Blast"],
        14: ["Flash Cannon"],
        25: ["Rock Slide"],
    },
    "Aggron": {
        1: ["Iron Head"],
        5: ["Flash Cannon"],
        12: ["Stone Edge"],
        22: ["Earthquake"],
        35: ["Body Slam"],
    },
    "Abra": {
        1: ["Confusion"],
        10: ["Psybeam"],
        20: ["Psychic"],
    },
    "Kadabra": {
        1: ["Confusion"],
        5: ["Psybeam"],
        15: ["Psychic"],
        25: ["Shadow Ball"],
    },
    "Alakazam": {
        1: ["Psybeam"],
        5: ["Psychic"],
        15: ["Shadow Ball"],
        28: ["Close Combat"],
        40: ["Phantom Force"],
    },
    "Ralts": {
        1: ["Confusion"],
        8: ["Psybeam"],
        18: ["Psychic"],
    },
    "Kirlia": {
        1: ["Psybeam"],
        5: ["Confusion"],
        15: ["Psychic"],
        25: ["Shadow Ball"],
    },
    "Gallade": {
        1: ["Psychic"],
        5: ["Close Combat"],
        12: ["Shadow Ball"],
        22: ["Karate Chop"],
        35: ["X-Scissor"],
        48: ["Phantom Force"],
    },
    "Bronzor": {
        1: ["Metal Claw"],
        5: ["Confusion"],
        14: ["Psychic"],
    },
    "Bronzong": {
        1: ["Confusion"],
        5: ["Iron Head"],
        12: ["Psychic"],
        22: ["Flash Cannon"],
        35: ["Earthquake"],
    },
    "Beldum": {
        1: ["Metal Claw"],
    },
    "Metang": {
        1: ["Metal Claw"],
        5: ["Confusion"],
        12: ["Iron Head"],
        22: ["Psychic"],
    },
    "Metagross": {
        1: ["Iron Head"],
        5: ["Psychic"],
        12: ["Flash Cannon"],
        20: ["Earthquake"],
        30: ["Body Slam"],
        45: ["Close Combat"],
    },
    "Pikachu": {
        1: ["Thunder Shock"],
        12: ["Thunderbolt"],
        30: ["Thunder"],
    },
    "Caterpie": {
        1: ["Scratch"],
        5: ["Bug Bite"],
    },
    "Metapod": {
        1: ["Scratch"],
    },
    "Butterfree": {
        1: ["Gust"],
        10: ["Bug Bite"],
        20: ["Air Slash"],
        30: ["X-Scissor"],
    },
    "Poliwag": {
        1: ["Bubble"],
        8: ["Water Gun"],
        15: ["Body Slam"],
    },
    "Poliwhirl": {
        1: ["Water Gun"],
        15: ["Surf"],
        25: ["Close Combat"],
    },
    "Poliwrath": {
        1: ["Surf"],
        10: ["Close Combat"],
        30: ["Hydro Pump"],
    },
}
