pokedex = {
    "Quadrabirr": {
        "type": ["Electric", "Flying"],
        "hp": 70,
        "attack": 60,
        "defence": 45,
        "speed": 120,
        "special": 80,
        "description": "The Four-Wing Bird Pokemon. Quadrabirr is a tiny, energetic bird Pokemon known for its brilliant golden feathers. Despite its small size, it is remarkably fast in the air. It is said that spotting a Quadrabirr brings good luck to travellers.",
    },
    "Dinovinery": {
        "type": ["Grass", "Poison"],
        "hp": 120,
        "attack": 60,
        "defence": 90,
        "speed": 50,
        "special": 75,
    },
    "Draponie": {
        "type": ["Dragon", "Fairy"],
        "hp": 80,
        "attack": 70,
        "defence": 90,
        "speed": 100,
        "special": 85,
    },
    "Prototype": {
        "type": ["Dragon", "Dark"],
        "hp": 90,
        "attack": 120,
        "defence": 70,
        "speed": 50,
        "special": 60,
    },
    "Debuner": {
        "type": ["Ground", "Poison"],
        "hp": 110,
        "attack": 60,
        "defence": 80,
        "speed": 70,
        "special": 55,
    },
    "Rasnail": {
        "type": ["Rock", "Bug"],
        "hp": 115,
        "attack": 65,
        "defence": 120,
        "speed": 20,
        "special": 45,
    },
    "Frodger": {
        "type": ["Dragon", "Fire"],
        "hp": 55,
        "attack": 85,
        "defence": 30,
        "speed": 35,
        "special": 70,
    },
    "Frogandi": {
        "type": ["Dragon", "Fire"],
        "hp": 70,
        "attack": 110,
        "defence": 40,
        "speed": 45,
        "special": 85,
    },
    "Frogainian": {
        "type": ["Dragon", "Fire"],
        "hp": 85,
        "attack": 35,
        "defence": 130,
        "speed": 55,
        "special": 65,
    },
    "Buliz": {
        "type": ["Dragon", "Water"],
        "hp": 60,
        "attack": 30,
        "defence": 90,
        "speed": 40,
        "special": 75,
    },
    "Bulits": {
        "type": ["Dragon", "Water"],
        "hp": 75,
        "attack": 40,
        "defence": 115,
        "speed": 50,
        "special": 85,
    },
    "Bulitzer": {
        "type": ["Dragon", "Water"],
        "hp": 85,
        "attack": 130,
        "defence": 35,
        "speed": 60,
        "special": 70,
    },
    "Falake": {
        "type": ["Dragon", "Grass"],
        "hp": 90,
        "attack": 50,
        "defence": 50,
        "speed": 40,
        "special": 65,
    },
    "Faelke": {
        "type": ["Dragon", "Grass"],
        "hp": 120,
        "attack": 60,
        "defence": 60,
        "speed": 50,
        "special": 75,
    },
    "Psyake": {
        "type": ["Dragon", "Grass"],
        "hp": 60,
        "attack": 70,
        "defence": 50,
        "speed": 135,
        "special": 110,
    },
    "Dratini": {
        "type": ["Dragon"],
        "hp": 41,
        "attack": 64,
        "defence": 45,
        "speed": 50,
        "special": 50,
    },
    "Dragonair": {
        "type": ["Dragon"],
        "hp": 61,
        "attack": 84,
        "defence": 65,
        "speed": 70,
        "special": 70,
    },
    "Dragonite": {
        "type": ["Dragon", "Flying"],
        "hp": 91,
        "attack": 134,
        "defence": 95,
        "speed": 80,
        "special": 100,
    },
    "Roggenrola": {
        "type": ["Rock"],
        "hp": 55,
        "attack": 75,
        "defence": 85,
        "speed": 15,
        "special": 25,
    },
    "Boldore": {
        "type": ["Rock"],
        "hp": 70,
        "attack": 105,
        "defence": 105,
        "speed": 20,
        "special": 45,
    },
    "Gigalith": {
        "type": ["Rock"],
        "hp": 85,
        "attack": 135,
        "defence": 130,
        "speed": 25,
        "special": 70,
    },
    "Pecharunt": {
        "type": ["Poison", "Ghost"],
        "hp": 88,
        "attack": 88,
        "defence": 160,
        "speed": 88,
        "special": 88,
    },
    "Zygarde-10": {
        "type": ["Dragon", "Ground"],
        "hp": 54,
        "attack": 100,
        "defence": 71,
        "speed": 115,
        "special": 73,
    },
    "Zygarde-50": {
        "type": ["Dragon", "Ground"],
        "hp": 108,
        "attack": 100,
        "defence": 121,
        "speed": 95,
        "special": 88,
    },
    "Zygarde-Complete": {
        "type": ["Dragon", "Ground"],
        "hp": 216,
        "attack": 100,
        "defence": 121,
        "speed": 85,
        "special": 93,
    },
    "Flamlet": {
        "type": ["Dragon", "Fire"],
        "hp": 40,
        "attack": 45,
        "defence": 35,
        "speed": 55,
        "special": 50,
    },
    "Serfling": {
        "type": ["Dragon", "Fire"],
        "hp": 60,
        "attack": 70,
        "defence": 50,
        "speed": 75,
        "special": 75,
    },
    "Serfyre": {
        "type": ["Dragon", "Fire"],
        "hp": 75,
        "attack": 95,
        "defence": 60,
        "speed": 90,
        "special": 100,
    },
    "Frostlet": {
        "type": ["Dragon", "Ice"],
        "hp": 55,
        "attack": 40,
        "defence": 55,
        "speed": 25,
        "special": 45,
    },
    "Glacilet": {
        "type": ["Dragon", "Ice"],
        "hp": 75,
        "attack": 60,
        "defence": 75,
        "speed": 35,
        "special": 65,
    },
    "Glaciwyrm": {
        "type": ["Dragon", "Ice"],
        "hp": 100,
        "attack": 80,
        "defence": 100,
        "speed": 40,
        "special": 90,
    },
    "Riplet": {
        "type": ["Dragon", "Water"],
        "hp": 45,
        "attack": 35,
        "defence": 45,
        "speed": 50,
        "special": 50,
    },
    "Aqualet": {
        "type": ["Dragon", "Water"],
        "hp": 65,
        "attack": 55,
        "defence": 65,
        "speed": 65,
        "special": 70,
    },
    "Aqualisk": {
        "type": ["Dragon", "Water"],
        "hp": 85,
        "attack": 75,
        "defence": 85,
        "speed": 80,
        "special": 95,
    },
    "Sparklet": {
        "type": ["Dragon", "Electric"],
        "hp": 35,
        "attack": 45,
        "defence": 25,
        "speed": 70,
        "special": 55,
    },
    "Voltlet": {
        "type": ["Dragon", "Electric"],
        "hp": 50,
        "attack": 65,
        "defence": 40,
        "speed": 95,
        "special": 75,
    },
    "Voltscale": {
        "type": ["Dragon", "Electric"],
        "hp": 65,
        "attack": 85,
        "defence": 50,
        "speed": 120,
        "special": 100,
    },
    "Ironlet": {
        "type": ["Dragon", "Steel"],
        "hp": 45,
        "attack": 55,
        "defence": 70,
        "speed": 20,
        "special": 25,
    },
    "Steelbit": {
        "type": ["Dragon", "Steel"],
        "hp": 65,
        "attack": 85,
        "defence": 100,
        "speed": 30,
        "special": 40,
    },
    "Ironmaw": {
        "type": ["Dragon", "Steel"],
        "hp": 80,
        "attack": 110,
        "defence": 130,
        "speed": 40,
        "special": 50,
    },
    "Misting": {
        "type": ["Dragon", "Ghost"],
        "hp": 35,
        "attack": 45,
        "defence": 30,
        "speed": 65,
        "special": 50,
    },
    "Phantling": {
        "type": ["Dragon", "Ghost"],
        "hp": 55,
        "attack": 70,
        "defence": 45,
        "speed": 90,
        "special": 72,
    },
    "Phantail": {
        "type": ["Dragon", "Ghost"],
        "hp": 70,
        "attack": 90,
        "defence": 60,
        "speed": 110,
        "special": 95,
    },
    # Gen 2
    "Horsea": {
        "type": ["Water"],
        "hp": 30,
        "attack": 40,
        "defence": 70,
        "speed": 60,
        "special": 70,
    },
    "Seadra": {
        "type": ["Water"],
        "hp": 55,
        "attack": 65,
        "defence": 95,
        "speed": 85,
        "special": 95,
    },
    "Kingdra": {
        "type": ["Water", "Dragon"],
        "hp": 75,
        "attack": 95,
        "defence": 95,
        "speed": 85,
        "special": 95,
    },
    # Gen 3
    "Bagon": {
        "type": ["Dragon"],
        "hp": 45,
        "attack": 75,
        "defence": 60,
        "speed": 50,
        "special": 40,
    },
    "Shelgon": {
        "type": ["Dragon"],
        "hp": 65,
        "attack": 95,
        "defence": 100,
        "speed": 50,
        "special": 60,
    },
    "Salamence": {
        "type": ["Dragon", "Flying"],
        "hp": 95,
        "attack": 135,
        "defence": 80,
        "speed": 100,
        "special": 110,
    },
    "Swablu": {
        "type": ["Normal", "Flying"],
        "hp": 45,
        "attack": 40,
        "defence": 60,
        "speed": 50,
        "special": 40,
    },
    "Altaria": {
        "type": ["Dragon", "Flying"],
        "hp": 75,
        "attack": 70,
        "defence": 90,
        "speed": 80,
        "special": 70,
    },
    "Trapinch": {
        "type": ["Bug"],
        "hp": 45,
        "attack": 100,
        "defence": 45,
        "speed": 10,
        "special": 45,
    },
    "Vibrava": {
        "type": ["Dragon", "Bug"],
        "hp": 50,
        "attack": 70,
        "defence": 50,
        "speed": 70,
        "special": 50,
    },
    "Flygon": {
        "type": ["Dragon", "Bug"],
        "hp": 80,
        "attack": 100,
        "defence": 80,
        "speed": 100,
        "special": 80,
    },
    "Latias": {
        "type": ["Dragon", "Psychic"],
        "hp": 80,
        "attack": 80,
        "defence": 90,
        "speed": 110,
        "special": 110,
    },
    "Latios": {
        "type": ["Dragon", "Psychic"],
        "hp": 80,
        "attack": 90,
        "defence": 80,
        "speed": 110,
        "special": 130,
    },
    "Rayquaza": {
        "type": ["Dragon", "Flying"],
        "hp": 105,
        "attack": 150,
        "defence": 90,
        "speed": 95,
        "special": 150,
    },
    # Gen 4
    "Gible": {
        "type": ["Dragon", "Ground"],
        "hp": 58,
        "attack": 70,
        "defence": 45,
        "speed": 42,
        "special": 40,
    },
    "Gabite": {
        "type": ["Dragon", "Ground"],
        "hp": 68,
        "attack": 90,
        "defence": 65,
        "speed": 82,
        "special": 50,
    },
    "Garchomp": {
        "type": ["Dragon", "Ground"],
        "hp": 108,
        "attack": 130,
        "defence": 95,
        "speed": 102,
        "special": 80,
    },
    "Dialga": {
        "type": ["Steel", "Dragon"],
        "hp": 100,
        "attack": 120,
        "defence": 120,
        "speed": 90,
        "special": 150,
    },
    "Palkia": {
        "type": ["Water", "Dragon"],
        "hp": 90,
        "attack": 120,
        "defence": 100,
        "speed": 100,
        "special": 150,
    },
    "Giratina": {
        "type": ["Ghost", "Dragon"],
        "hp": 150,
        "attack": 100,
        "defence": 120,
        "speed": 90,
        "special": 100,
    },
    # Gen 5
    "Axew": {
        "type": ["Dragon"],
        "hp": 46,
        "attack": 87,
        "defence": 60,
        "speed": 57,
        "special": 30,
    },
    "Fraxure": {
        "type": ["Dragon"],
        "hp": 66,
        "attack": 117,
        "defence": 70,
        "speed": 67,
        "special": 40,
    },
    "Haxorus": {
        "type": ["Dragon"],
        "hp": 76,
        "attack": 147,
        "defence": 90,
        "speed": 97,
        "special": 60,
    },
    "Deino": {
        "type": ["Dark"],
        "hp": 52,
        "attack": 65,
        "defence": 50,
        "speed": 38,
        "special": 45,
    },
    "Zweilous": {
        "type": ["Dragon", "Dark"],
        "hp": 72,
        "attack": 85,
        "defence": 70,
        "speed": 58,
        "special": 65,
    },
    "Hydreigon": {
        "type": ["Dark", "Dragon"],
        "hp": 92,
        "attack": 105,
        "defence": 90,
        "speed": 98,
        "special": 125,
    },
    "Druddigon": {
        "type": ["Dragon"],
        "hp": 77,
        "attack": 120,
        "defence": 90,
        "speed": 48,
        "special": 60,
    },
    "Reshiram": {
        "type": ["Dragon", "Fire"],
        "hp": 100,
        "attack": 120,
        "defence": 100,
        "speed": 90,
        "special": 150,
    },
    "Zekrom": {
        "type": ["Dragon", "Electric"],
        "hp": 100,
        "attack": 150,
        "defence": 120,
        "speed": 90,
        "special": 120,
    },
    "Kyurem": {
        "type": ["Dragon", "Ice"],
        "hp": 125,
        "attack": 130,
        "defence": 90,
        "speed": 95,
        "special": 130,
    },
    # Gen 6
    "Goomy": {
        "type": ["Dragon"],
        "hp": 45,
        "attack": 50,
        "defence": 35,
        "speed": 40,
        "special": 55,
    },
    "Sliggoo": {
        "type": ["Dragon"],
        "hp": 68,
        "attack": 75,
        "defence": 53,
        "speed": 60,
        "special": 83,
    },
    "Goodra": {
        "type": ["Dragon"],
        "hp": 90,
        "attack": 100,
        "defence": 70,
        "speed": 80,
        "special": 110,
    },
    "Noibat": {
        "type": ["Flying", "Dragon"],
        "hp": 40,
        "attack": 30,
        "defence": 35,
        "speed": 55,
        "special": 45,
    },
    "Noivern": {
        "type": ["Flying", "Dragon"],
        "hp": 85,
        "attack": 70,
        "defence": 80,
        "speed": 123,
        "special": 97,
    },
    "Tyrunt": {
        "type": ["Rock", "Dragon"],
        "hp": 58,
        "attack": 89,
        "defence": 77,
        "speed": 48,
        "special": 45,
    },
    "Tyrantrum": {
        "type": ["Rock", "Dragon"],
        "hp": 82,
        "attack": 121,
        "defence": 119,
        "speed": 71,
        "special": 69,
    },
    # Gen 7
    "Jangmo-o": {
        "type": ["Dragon"],
        "hp": 45,
        "attack": 55,
        "defence": 65,
        "speed": 45,
        "special": 35,
    },
    "Hakamo-o": {
        "type": ["Dragon", "Fighting"],
        "hp": 55,
        "attack": 75,
        "defence": 90,
        "speed": 65,
        "special": 65,
    },
    "Kommo-o": {
        "type": ["Dragon", "Fighting"],
        "hp": 75,
        "attack": 110,
        "defence": 125,
        "speed": 85,
        "special": 100,
    },
    "Drampa": {
        "type": ["Normal", "Dragon"],
        "hp": 78,
        "attack": 60,
        "defence": 85,
        "speed": 36,
        "special": 135,
    },
    "Turtonator": {
        "type": ["Fire", "Dragon"],
        "hp": 60,
        "attack": 78,
        "defence": 135,
        "speed": 36,
        "special": 91,
    },
    "Applin": {
        "type": ["Grass", "Dragon"],
        "hp": 40,
        "attack": 40,
        "defence": 80,
        "speed": 20,
        "special": 40,
    },
    "Flapple": {
        "type": ["Grass", "Dragon"],
        "hp": 70,
        "attack": 110,
        "defence": 80,
        "speed": 70,
        "special": 95,
    },
    # Gen 8
    "Dreepy": {
        "type": ["Dragon", "Ghost"],
        "hp": 28,
        "attack": 60,
        "defence": 30,
        "speed": 82,
        "special": 40,
    },
    "Drakloak": {
        "type": ["Dragon", "Ghost"],
        "hp": 68,
        "attack": 80,
        "defence": 50,
        "speed": 102,
        "special": 60,
    },
    "Dragapult": {
        "type": ["Dragon", "Ghost"],
        "hp": 88,
        "attack": 120,
        "defence": 75,
        "speed": 142,
        "special": 100,
    },
    "Duraludon": {
        "type": ["Steel", "Dragon"],
        "hp": 70,
        "attack": 95,
        "defence": 115,
        "speed": 85,
        "special": 120,
    },
    # Gen 9
    "Frigibax": {
        "type": ["Dragon", "Ice"],
        "hp": 65,
        "attack": 75,
        "defence": 45,
        "speed": 55,
        "special": 35,
    },
    "Arctibax": {
        "type": ["Dragon", "Ice"],
        "hp": 90,
        "attack": 95,
        "defence": 66,
        "speed": 62,
        "special": 45,
    },
    "Baxcalibur": {
        "type": ["Dragon", "Ice"],
        "hp": 115,
        "attack": 145,
        "defence": 92,
        "speed": 87,
        "special": 75,
    },
    "Cyclizar": {
        "type": ["Dragon", "Normal"],
        "hp": 70,
        "attack": 95,
        "defence": 65,
        "speed": 121,
        "special": 85,
    },
    "Tatsugiri": {
        "type": ["Dragon", "Water"],
        "hp": 68,
        "attack": 50,
        "defence": 60,
        "speed": 82,
        "special": 120,
    },
    # Gen 1 additions
    "Magikarp": {
        "type": ["Water"],
        "hp": 20,
        "attack": 10,
        "defence": 55,
        "speed": 80,
        "special": 15,
    },
    "Gyarados": {
        "type": ["Water", "Flying"],
        "hp": 95,
        "attack": 125,
        "defence": 79,
        "speed": 81,
        "special": 60,
    },
    "Scyther": {
        "type": ["Bug", "Flying"],
        "hp": 70,
        "attack": 110,
        "defence": 80,
        "speed": 105,
        "special": 55,
    },
    "Scizor": {
        "type": ["Bug", "Steel"],
        "hp": 70,
        "attack": 130,
        "defence": 100,
        "speed": 65,
        "special": 55,
    },
    # Gen 2 additions
    "Misdreavus": {
        "type": ["Ghost"],
        "hp": 60,
        "attack": 60,
        "defence": 60,
        "speed": 85,
        "special": 85,
    },
    "Mismagius": {
        "type": ["Ghost"],
        "hp": 60,
        "attack": 60,
        "defence": 60,
        "speed": 105,
        "special": 105,
    },
    "Sneasel": {
        "type": ["Dark", "Ice"],
        "hp": 55,
        "attack": 95,
        "defence": 55,
        "speed": 115,
        "special": 35,
    },
    "Weavile": {
        "type": ["Dark", "Ice"],
        "hp": 70,
        "attack": 120,
        "defence": 65,
        "speed": 125,
        "special": 45,
    },
    "Houndour": {
        "type": ["Dark", "Fire"],
        "hp": 45,
        "attack": 60,
        "defence": 30,
        "speed": 65,
        "special": 80,
    },
    "Houndoom": {
        "type": ["Dark", "Fire"],
        "hp": 75,
        "attack": 90,
        "defence": 50,
        "speed": 95,
        "special": 110,
    },
    "Gligar": {
        "type": ["Ground", "Flying"],
        "hp": 65,
        "attack": 75,
        "defence": 105,
        "speed": 85,
        "special": 35,
    },
    "Gliscor": {
        "type": ["Ground", "Flying"],
        "hp": 75,
        "attack": 95,
        "defence": 125,
        "speed": 95,
        "special": 45,
    },
    "Larvitar": {
        "type": ["Rock", "Ground"],
        "hp": 50,
        "attack": 64,
        "defence": 50,
        "speed": 41,
        "special": 45,
    },
    "Pupitar": {
        "type": ["Rock", "Ground"],
        "hp": 70,
        "attack": 84,
        "defence": 70,
        "speed": 51,
        "special": 65,
    },
    "Tyranitar": {
        "type": ["Rock", "Dark"],
        "hp": 100,
        "attack": 134,
        "defence": 110,
        "speed": 61,
        "special": 95,
    },
    # Gen 3 additions
    "Aron": {
        "type": ["Steel", "Rock"],
        "hp": 50,
        "attack": 70,
        "defence": 100,
        "speed": 30,
        "special": 40,
    },
    "Lairon": {
        "type": ["Steel", "Rock"],
        "hp": 60,
        "attack": 90,
        "defence": 140,
        "speed": 40,
        "special": 50,
    },
    "Aggron": {
        "type": ["Steel", "Rock"],
        "hp": 70,
        "attack": 110,
        "defence": 180,
        "speed": 50,
        "special": 60,
    },
    "Beldum": {
        "type": ["Steel", "Psychic"],
        "hp": 40,
        "attack": 55,
        "defence": 80,
        "speed": 30,
        "special": 35,
    },
    "Metang": {
        "type": ["Steel", "Psychic"],
        "hp": 60,
        "attack": 75,
        "defence": 100,
        "speed": 50,
        "special": 55,
    },
    "Metagross": {
        "type": ["Steel", "Psychic"],
        "hp": 80,
        "attack": 135,
        "defence": 130,
        "speed": 70,
        "special": 95,
    },
    # Gen 1 additions
    "Gastly": {
        "type": ["Ghost", "Poison"],
        "hp": 30, "attack": 35, "defence": 30, "speed": 80, "special": 100,
    },
    "Haunter": {
        "type": ["Ghost", "Poison"],
        "hp": 45, "attack": 50, "defence": 45, "speed": 95, "special": 115,
    },
    "Gengar": {
        "type": ["Ghost", "Poison"],
        "hp": 60, "attack": 65, "defence": 60, "speed": 110, "special": 130,
    },
    "Onix": {
        "type": ["Rock", "Ground"],
        "hp": 35, "attack": 45, "defence": 160, "speed": 70, "special": 30,
    },
    "Steelix": {
        "type": ["Steel", "Ground"],
        "hp": 75, "attack": 85, "defence": 200, "speed": 30, "special": 55,
    },
    # Gen 4 additions
    "Cranidos": {

        "type": ["Rock"],
        "hp": 67, "attack": 125, "defence": 40, "speed": 58, "special": 30,
    },
    "Rampardos": {
        "type": ["Rock"],
        "hp": 97, "attack": 165, "defence": 60, "speed": 58, "special": 65,
    },
    "Honedge": {
        "type": ["Steel", "Ghost"],
        "hp": 45, "attack": 80, "defence": 100, "speed": 28, "special": 35,
    },
    "Doublade": {
        "type": ["Steel", "Ghost"],
        "hp": 59, "attack": 110, "defence": 150, "speed": 35, "special": 45,
    },
    "Aegislash": {
        "type": ["Steel", "Ghost"],
        "hp": 60, "attack": 100, "defence": 100, "speed": 60, "special": 100,
    },
    "Rookidee": {
        "type": ["Flying"],
        "hp": 38, "attack": 47, "defence": 35, "speed": 57, "special": 33,
    },
    "Corvisquire": {
        "type": ["Flying"],
        "hp": 68, "attack": 67, "defence": 55, "speed": 77, "special": 43,
    },
    "Corviknight": {
        "type": ["Flying", "Steel"],
        "hp": 98, "attack": 87, "defence": 105, "speed": 67, "special": 53,
    },
    # Gen 5 additions
    "Zorua": {
        "type": ["Dark"],
        "hp": 40, "attack": 65, "defence": 40, "speed": 65, "special": 80,
    },
    "Zoroark": {
        "type": ["Dark"],
        "hp": 60, "attack": 105, "defence": 60, "speed": 105, "special": 120,
    },
    "Sandile": {
        "type": ["Ground", "Dark"],
        "hp": 50, "attack": 72, "defence": 35, "speed": 65, "special": 35,
    },
    "Krokorok": {
        "type": ["Ground", "Dark"],
        "hp": 60, "attack": 82, "defence": 45, "speed": 74, "special": 45,
    },
    "Krookodile": {
        "type": ["Ground", "Dark"],
        "hp": 95, "attack": 117, "defence": 70, "speed": 92, "special": 65,
    },
    "Pawniard": {
        "type": ["Dark", "Steel"],
        "hp": 45, "attack": 85, "defence": 70, "speed": 60, "special": 40,
    },
    "Bisharp": {
        "type": ["Dark", "Steel"],
        "hp": 65, "attack": 125, "defence": 100, "speed": 70, "special": 60,
    },
    "Kingambit": {
        "type": ["Dark", "Steel"],
        "hp": 100, "attack": 135, "defence": 120, "speed": 50, "special": 60,
    },
    "Litwick": {
        "type": ["Ghost", "Fire"],
        "hp": 50, "attack": 30, "defence": 55, "speed": 20, "special": 65,
    },
    "Lampent": {
        "type": ["Ghost", "Fire"],
        "hp": 60, "attack": 40, "defence": 60, "speed": 55, "special": 95,
    },
    "Chandelure": {
        "type": ["Ghost", "Fire"],
        "hp": 60, "attack": 55, "defence": 90, "speed": 80, "special": 145,
    },
    # Gen 7 additions
    "Salandit": {
        "type": ["Poison", "Fire"],
        "hp": 48, "attack": 44, "defence": 40, "speed": 77, "special": 71,
    },
    "Salazzle": {
        "type": ["Poison", "Fire"],
        "hp": 68, "attack": 64, "defence": 60, "speed": 117, "special": 111,
    },
    # Gen 8 additions
    "Toxel": {
        "type": ["Electric", "Poison"],
        "hp": 40, "attack": 38, "defence": 35, "speed": 40, "special": 54,
    },
    "Toxtricity": {
        "type": ["Electric", "Poison"],
        "hp": 75, "attack": 98, "defence": 70, "speed": 75, "special": 114,
    },
    # Gen 9 additions
    "Roaring Moon": {
        "type": ["Dragon", "Dark"],
        "hp": 105, "attack": 139, "defence": 71, "speed": 119, "special": 55,
    },
    "Walking Wake": {
        "type": ["Water", "Dragon"],
        "hp": 99, "attack": 83, "defence": 91, "speed": 109, "special": 125,
    },
    # Team Fairy Pokemon
    "Clefairy": {
        "type": ["Fairy"],
        "hp": 70,
        "attack": 45,
        "defence": 48,
        "speed": 35,
        "special": 60,
    },
    "Clefable": {
        "type": ["Fairy"],
        "hp": 95,
        "attack": 70,
        "defence": 73,
        "speed": 60,
        "special": 95,
    },
    "Snubbull": {
        "type": ["Fairy"],
        "hp": 60,
        "attack": 80,
        "defence": 50,
        "speed": 30,
        "special": 40,
    },
    "Granbull": {
        "type": ["Fairy"],
        "hp": 90,
        "attack": 120,
        "defence": 75,
        "speed": 45,
        "special": 60,
    },
    "Sylveon": {
        "type": ["Fairy"],
        "hp": 95,
        "attack": 65,
        "defence": 65,
        "speed": 60,
        "special": 110,
    },
    "Mimikyu": {
        "type": ["Ghost", "Fairy"],
        "hp": 55,
        "attack": 90,
        "defence": 80,
        "speed": 96,
        "special": 50,
    },
    "Togekiss": {
        "type": ["Fairy", "Flying"],
        "hp": 85,
        "attack": 50,
        "defence": 95,
        "speed": 80,
        "special": 120,
    },
    "Gardevoir": {
        "type": ["Psychic", "Fairy"],
        "hp": 68,
        "attack": 65,
        "defence": 65,
        "speed": 80,
        "special": 125,
    },
    "Xerneas": {
        "type": ["Fairy"],
        "hp": 126,
        "attack": 131,
        "defence": 95,
        "speed": 99,
        "special": 131,
    },
    # Psychic types
    "Abra": {
        "type": ["Psychic"],
        "hp": 25,
        "attack": 20,
        "defence": 15,
        "speed": 90,
        "special": 105,
    },
    "Kadabra": {
        "type": ["Psychic"],
        "hp": 40,
        "attack": 35,
        "defence": 30,
        "speed": 105,
        "special": 120,
    },
    "Alakazam": {
        "type": ["Psychic"],
        "hp": 55,
        "attack": 50,
        "defence": 45,
        "speed": 120,
        "special": 135,
    },
    "Ralts": {
        "type": ["Psychic"],
        "hp": 28,
        "attack": 25,
        "defence": 25,
        "speed": 40,
        "special": 45,
    },
    "Kirlia": {
        "type": ["Psychic"],
        "hp": 38,
        "attack": 35,
        "defence": 35,
        "speed": 50,
        "special": 65,
    },
    "Gallade": {
        "type": ["Psychic", "Fighting"],
        "hp": 68,
        "attack": 125,
        "defence": 65,
        "speed": 80,
        "special": 65,
    },
    "Bronzor": {
        "type": ["Steel", "Psychic"],
        "hp": 57,
        "attack": 24,
        "defence": 86,
        "speed": 23,
        "special": 24,
    },
    "Bronzong": {
        "type": ["Steel", "Psychic"],
        "hp": 67,
        "attack": 89,
        "defence": 116,
        "speed": 33,
        "special": 79,
    },
    "Pikachu": {
        "type": ["Electric"],
        "hp": 35,
        "attack": 55,
        "defence": 40,
        "speed": 90,
        "special": 50,
    },
    "Caterpie": {
        "type": ["Bug"],
        "hp": 45,
        "attack": 30,
        "defence": 35,
        "speed": 45,
        "special": 20,
    },
}
