routes = {
    "Route 1": {
        "description": "A dusty path stretching north from Bakil City. Dragon whelps bask in the afternoon heat.",
        "wild_pokemon": [
            {"name": "Trapinch", "min_level": 3, "max_level": 5, "rate": 40},
            {"name": "Dreepy",   "min_level": 3, "max_level": 5, "rate": 40},
            {"name": "Gible",    "min_level": 4, "max_level": 6, "rate": 20},
        ],
        "trainers": [
            {
                "name": "Teymur",
                "class": "Young Trainer",
                "team": [("Trapinch", 4)],
                "greeting": "Teymur: Dragons are the best Pokémon ever! Come on, battle me!",
                "defeat_text": "Teymur: You're really good... I'm gonna train way harder.",
                "reward": 200,
            },
            {
                "name": "Nigar",
                "class": "Young Trainer",
                "team": [("Dreepy", 5)],
                "greeting": "Nigar: My Dreepy is a ghost AND a dragon. Nobody can beat that!",
                "defeat_text": "Nigar: Okay... maybe someone can beat that.",
                "reward": 250,
            },
        ],
    },

    "Route 2": {
        "description": "A wider road lined with tall grass. Trainers come here to catch their first Gible.",
        "wild_pokemon": [
            {"name": "Trapinch",  "min_level": 6, "max_level": 8,  "rate": 35},
            {"name": "Dinovinery","min_level": 6, "max_level": 8,  "rate": 25},
            {"name": "Pikachu",   "min_level": 5, "max_level": 8,  "rate": 25},
            {"name": "Gible",     "min_level": 7, "max_level": 9,  "rate": 14},
            {"name": "Vibrava",   "min_level": 8, "max_level": 10, "rate": 1},
        ],
        "trainers": [
            {
                "name": "Jake",
                "class": "Young Trainer",
                "team": [("Trapinch", 6), ("Pikachu", 6)],
                "greeting": "Jake: I caught a Pikachu AND a Trapinch! I'm basically unstoppable!",
                "defeat_text": "Jake: Okay... I might need a few more levels first.",
                "reward": 300,
            },
            {
                "name": "Lily",
                "class": "Young Trainer",
                "team": [("Gible", 7), ("Dinovinery", 7)],
                "greeting": "Lily: Gible is going to be a Garchomp one day. And then you'll be sorry.",
                "defeat_text": "Lily: Just you wait. Garchomp. One day.",
                "reward": 350,
            },
            {
                "name": "Owen",
                "class": "Young Trainer",
                "team": [("Pikachu", 7), ("Trapinch", 8)],
                "greeting": "Owen: Dad says anyone heading to Saffron City must be serious. Are you serious?",
                "defeat_text": "Owen: ...Yeah. You're serious.",
                "reward": 400,
            },
        ],
    },

    "Route 3": {
        "description": "The final stretch before Saffron City. Serious trainers only.",
        "wild_pokemon": [
            {"name": "Trapinch",  "min_level": 9,  "max_level": 11, "rate": 35},
            {"name": "Dinovinery","min_level": 9,  "max_level": 11, "rate": 25},
            {"name": "Pikachu",   "min_level": 8,  "max_level": 11, "rate": 25},
            {"name": "Gible",     "min_level": 10, "max_level": 12, "rate": 14},
            {"name": "Vibrava",   "min_level": 11, "max_level": 13, "rate": 1},
        ],
        "trainers": [
            {
                "name": "Emma",
                "class": "Young Trainer",
                "team": [("Trapinch", 9), ("Gible", 9)],
                "greeting": "Emma: Saffron's gym is just ahead! I'm going to win my first badge!",
                "defeat_text": "Emma: Hmm... maybe I should train on this route a bit longer.",
                "reward": 450,
            },
            {
                "name": "Tom",
                "class": "Young Trainer",
                "team": [("Dreepy", 10), ("Pikachu", 9)],
                "greeting": "Tom: Hey, do you know anything about Sabina? The gym leader? Is she scary?",
                "defeat_text": "Tom: Great. I can't beat a random trainer. I'm definitely not ready for the gym.",
                "reward": 500,
            },
            {
                "name": "Claire",
                "class": "Young Trainer",
                "team": [("Gible", 11), ("Dinovinery", 10)],
                "greeting": "Claire: My brother beat Sabina last year. I'm going to beat her this year. Starting with you!",
                "defeat_text": "Claire: You're better than my brother was. That's actually a compliment.",
                "reward": 550,
            },
        ],
    },

    "Route 4": {
        "description": "Rolling hills north of Saffron City. Wild Pokémon are noticeably stronger here.",
        "wild_pokemon": [
            {"name": "Bagon",      "min_level": 14, "max_level": 17, "rate": 35},
            {"name": "Horsea",     "min_level": 14, "max_level": 17, "rate": 30},
            {"name": "Zorua",      "min_level": 14, "max_level": 16, "rate": 20},
            {"name": "Dinovinery", "min_level": 13, "max_level": 16, "rate": 15},
        ],
        "trainers": [
            {
                "name": "Jade",
                "class": "Young Trainer",
                "team": [("Bagon", 14), ("Horsea", 14)],
                "greeting": "Jade: I've been training on this route for weeks. You won't get past me!",
                "defeat_text": "Jade: Okay... maybe I needed a few more weeks.",
                "reward": 700,
            },
            {
                "name": "Max",
                "class": "Young Trainer",
                "team": [("Zorua", 15), ("Dinovinery", 15)],
                "greeting": "Max: Zorua can disguise itself as anything. Good luck figuring out what you're fighting.",
                "defeat_text": "Max: You didn't even seem confused. Impressive.",
                "reward": 750,
            },
            {
                "name": "Kyle",
                "class": "Young Trainer",
                "team": [("Bagon", 16), ("Horsea", 15)],
                "greeting": "Kyle: I caught both of these here today. Fresh and fired up!",
                "defeat_text": "Kyle: Fresh caught but not trained enough. I see the problem.",
                "reward": 800,
            },
        ],
    },

    "Route 5": {
        "description": "A foggy valley. Cold air drifts south — a sign of what lies further north.",
        "wild_pokemon": [
            {"name": "Bagon",   "min_level": 15, "max_level": 18, "rate": 25},
            {"name": "Horsea",  "min_level": 15, "max_level": 18, "rate": 25},
            {"name": "Zorua",   "min_level": 15, "max_level": 17, "rate": 25},
            {"name": "Sneasel", "min_level": 14, "max_level": 17, "rate": 25},
        ],
        "trainers": [
            {
                "name": "Rex",
                "class": "Young Trainer",
                "team": [("Zorua", 16), ("Sneasel", 15)],
                "greeting": "Rex: Dark types never fall for tricks. Which means I never fall for tricks either.",
                "defeat_text": "Rex: ...Guess you don't fall for tricks either.",
                "reward": 850,
            },
            {
                "name": "Holly",
                "class": "Young Trainer",
                "team": [("Horsea", 16), ("Bagon", 17)],
                "greeting": "Holly: I've been waiting here for a strong trainer. Finally someone shows up.",
                "defeat_text": "Holly: Even stronger than I hoped. Well done.",
                "reward": 900,
            },
            {
                "name": "Vera",
                "class": "Young Trainer",
                "team": [("Sneasel", 17), ("Zorua", 17), ("Bagon", 16)],
                "greeting": "Vera: Three Pokémon. You ready for that?",
                "defeat_text": "Vera: You were ready for that.",
                "reward": 950,
            },
        ],
    },

    "Route 6": {
        "description": "A forested road. Evolved Pokémon are starting to appear — things are getting serious.",
        "wild_pokemon": [
            {"name": "Shelgon",    "min_level": 16, "max_level": 19, "rate": 20},
            {"name": "Seadra",     "min_level": 16, "max_level": 19, "rate": 20},
            {"name": "Zorua",      "min_level": 16, "max_level": 18, "rate": 25},
            {"name": "Sneasel",    "min_level": 16, "max_level": 18, "rate": 20},
            {"name": "Misdreavus", "min_level": 15, "max_level": 18, "rate": 15},
        ],
        "trainers": [
            {
                "name": "Cole",
                "class": "Young Trainer",
                "team": [("Shelgon", 17), ("Zorua", 16)],
                "greeting": "Cole: My Shelgon evolved last week. It's basically unstoppable now.",
                "defeat_text": "Cole: ...Basically unstoppable. Not actually unstoppable. Got it.",
                "reward": 1000,
            },
            {
                "name": "Nina",
                "class": "Young Trainer",
                "team": [("Seadra", 18), ("Sneasel", 17)],
                "greeting": "Nina: The fog on this route hides a lot. You'd better be ready for anything.",
                "defeat_text": "Nina: You were ready for everything. Fair enough.",
                "reward": 1050,
            },
            {
                "name": "Oliver",
                "class": "Young Trainer",
                "team": [("Misdreavus", 18), ("Shelgon", 18)],
                "greeting": "Oliver: Ghost and Dragon. You tell me which one scares you more.",
                "defeat_text": "Oliver: Neither. The answer was neither. Noted.",
                "reward": 1100,
            },
        ],
    },

    "Route 7": {
        "description": "The last stretch before Goldenrod City. Only serious trainers make it this far.",
        "wild_pokemon": [
            {"name": "Shelgon",    "min_level": 17, "max_level": 20, "rate": 20},
            {"name": "Seadra",     "min_level": 17, "max_level": 20, "rate": 20},
            {"name": "Misdreavus", "min_level": 17, "max_level": 19, "rate": 25},
            {"name": "Zorua",      "min_level": 17, "max_level": 19, "rate": 20},
            {"name": "Quadrabirr", "min_level": 16, "max_level": 19, "rate": 15},
        ],
        "trainers": [
            {
                "name": "Zoe",
                "class": "Young Trainer",
                "team": [("Zorua", 18), ("Misdreavus", 17)],
                "greeting": "Zoe: Dark and Ghost. Let's see how you handle things you can't easily hit.",
                "defeat_text": "Zoe: You handled it fine. Ugh.",
                "reward": 1150,
            },
            {
                "name": "Brad",
                "class": "Young Trainer",
                "team": [("Seadra", 19), ("Shelgon", 18)],
                "greeting": "Brad: Goldenrod's just ahead. I'm going to beat you and walk in feeling great.",
                "defeat_text": "Brad: ...I'll still walk in. Just not feeling great.",
                "reward": 1200,
            },
            {
                "name": "Lea",
                "class": "Ace Trainer",
                "team": [("Misdreavus", 19), ("Seadra", 19), ("Shelgon", 20)],
                "greeting": "Lea: You've come a long way from Bakil City. Prove you deserve to walk through those gates.",
                "defeat_text": "Lea: You deserve it. Goldenrod is waiting.",
                "reward": 1300,
            },
        ],
    },

    "Route 8": {
        "description": "Rolling plains east of Goldenrod City. The city noise fades fast out here.",
        "wild_pokemon": [
            {"name": "Deino",   "min_level": 20, "max_level": 23, "rate": 30},
            {"name": "Axew",    "min_level": 21, "max_level": 23, "rate": 25},
            {"name": "Sandile", "min_level": 20, "max_level": 22, "rate": 25},
            {"name": "Swablu",  "min_level": 20, "max_level": 22, "rate": 20},
        ],
        "trainers": [
            {
                "name": "Eric",
                "class": "Young Trainer",
                "team": [("Deino", 21), ("Sandile", 20)],
                "greeting": "Eric: I've been training every day since Goldenrod opened. Don't think leaving the city means it gets easier!",
                "defeat_text": "Eric: ...Okay. It gets easier. But not by much!",
                "reward": 1250,
            },
            {
                "name": "Grace",
                "class": "Young Trainer",
                "team": [("Deino", 22), ("Axew", 21)],
                "greeting": "Grace: Deino can't even see you, and it still wins. That's how good it is.",
                "defeat_text": "Grace: ...It could see you coming apparently.",
                "reward": 1300,
            },
            {
                "name": "Ryan",
                "class": "Young Trainer",
                "team": [("Sandile", 22), ("Swablu", 21), ("Deino", 22)],
                "greeting": "Ryan: Sand and shadow, that's my style. Ready?",
                "defeat_text": "Ryan: Guess my style needs some work.",
                "reward": 1400,
            },
        ],
    },

    "Route 9": {
        "description": "A dry canyon carved by an ancient river. Echoes carry far out here.",
        "wild_pokemon": [
            {"name": "Deino",  "min_level": 22, "max_level": 24, "rate": 30},
            {"name": "Axew",   "min_level": 22, "max_level": 24, "rate": 20},
            {"name": "Noibat", "min_level": 21, "max_level": 23, "rate": 25},
            {"name": "Gligar", "min_level": 21, "max_level": 24, "rate": 25},
        ],
        "trainers": [
            {
                "name": "Victor",
                "class": "Young Trainer",
                "team": [("Deino", 22), ("Gligar", 21)],
                "greeting": "Victor: These canyons echo. Which means everyone will hear when I beat you.",
                "defeat_text": "Victor: Everyone will hear... that I lost. Great.",
                "reward": 1350,
            },
            {
                "name": "Kate",
                "class": "Young Trainer",
                "team": [("Noibat", 22), ("Axew", 23)],
                "greeting": "Kate: Noibat navigates by sound. It already knows exactly where your weak points are.",
                "defeat_text": "Kate: Apparently knowing isn't the same as hitting.",
                "reward": 1400,
            },
            {
                "name": "Chloe",
                "class": "Young Trainer",
                "team": [("Gligar", 23), ("Noibat", 22), ("Deino", 23)],
                "greeting": "Chloe: My Gligar has clawed its way across every route from here to the coast. It won't fall to you.",
                "defeat_text": "Chloe: It fell to you specifically. That stings.",
                "reward": 1500,
            },
        ],
    },

    "Route 10": {
        "description": "A wide river valley. The air turns damp and wild Pokémon grow bolder.",
        "wild_pokemon": [
            {"name": "Dratini", "min_level": 22, "max_level": 25, "rate": 20},
            {"name": "Poliwag", "min_level": 22, "max_level": 25, "rate": 25},
            {"name": "Goomy",   "min_level": 22, "max_level": 24, "rate": 25},
            {"name": "Noibat",  "min_level": 22, "max_level": 24, "rate": 20},
            {"name": "Riplet",  "min_level": 23, "max_level": 25, "rate": 10},
        ],
        "trainers": [
            {
                "name": "Nathan",
                "class": "Young Trainer",
                "team": [("Poliwag", 23), ("Goomy", 22)],
                "greeting": "Nathan: The river slows you down. That's exactly when I strike.",
                "defeat_text": "Nathan: You weren't slowed down enough.",
                "reward": 1450,
            },
            {
                "name": "Alice",
                "class": "Young Trainer",
                "team": [("Dratini", 24), ("Riplet", 23)],
                "greeting": "Alice: Dratini live in this river. I've been raising mine since it was a hatchling.",
                "defeat_text": "Alice: You beat something I raised from a hatchling. I'm going to need a minute.",
                "reward": 1500,
            },
            {
                "name": "Ross",
                "class": "Young Trainer",
                "team": [("Poliwag", 24), ("Goomy", 24), ("Dratini", 24)],
                "greeting": "Ross: Three water Pokémon. You're basically already wet.",
                "defeat_text": "Ross: You stayed dry. Impressive.",
                "reward": 1600,
            },
        ],
    },

    "Route 11": {
        "description": "Rocky cliffs rising toward the sea. Tough Pokémon nest in the crevices.",
        "wild_pokemon": [
            {"name": "Larvitar",  "min_level": 23, "max_level": 26, "rate": 25},
            {"name": "Jangmo-o",  "min_level": 24, "max_level": 26, "rate": 20},
            {"name": "Dratini",   "min_level": 23, "max_level": 26, "rate": 20},
            {"name": "Gligar",    "min_level": 23, "max_level": 25, "rate": 20},
            {"name": "Noibat",    "min_level": 23, "max_level": 25, "rate": 15},
        ],
        "trainers": [
            {
                "name": "Nick",
                "class": "Young Trainer",
                "team": [("Jangmo-o", 24), ("Larvitar", 23)],
                "greeting": "Nick: These cliffs are Jangmo-o territory. Fall back now or get rattled.",
                "defeat_text": "Nick: You rattled us instead. Fair.",
                "reward": 1550,
            },
            {
                "name": "Nora",
                "class": "Young Trainer",
                "team": [("Larvitar", 25), ("Dratini", 24)],
                "greeting": "Nora: Larvitar looks small, but it eats mountains. Literally.",
                "defeat_text": "Nora: It couldn't eat you though. Something to consider.",
                "reward": 1600,
            },
            {
                "name": "Evan",
                "class": "Young Trainer",
                "team": [("Jangmo-o", 25), ("Gligar", 24), ("Larvitar", 25)],
                "greeting": "Evan: The coast is just over that ridge. I'm the last thing standing between you and Slateport.",
                "defeat_text": "Evan: Coast is yours then. Go ahead.",
                "reward": 1700,
            },
        ],
    },

    "Route 12": {
        "description": "A seaside road. Salt in the air, waves below, and Slateport City just ahead.",
        "wild_pokemon": [
            {"name": "Tatsugiri", "min_level": 24, "max_level": 27, "rate": 25},
            {"name": "Aqualet",   "min_level": 25, "max_level": 27, "rate": 20},
            {"name": "Dratini",   "min_level": 24, "max_level": 27, "rate": 20},
            {"name": "Poliwag",   "min_level": 24, "max_level": 27, "rate": 20},
            {"name": "Riplet",    "min_level": 24, "max_level": 27, "rate": 15},
        ],
        "trainers": [
            {
                "name": "Laura",
                "class": "Young Trainer",
                "team": [("Tatsugiri", 25), ("Poliwag", 24)],
                "greeting": "Laura: The sea air makes my Pokémon stronger. Yours? Probably not.",
                "defeat_text": "Laura: Sea air apparently helps everyone.",
                "reward": 1650,
            },
            {
                "name": "Sophie",
                "class": "Young Trainer",
                "team": [("Aqualet", 26), ("Riplet", 25)],
                "greeting": "Sophie: Tatsugiri hides inside Dondozo. Mine doesn't have a Dondozo, but it's still terrifying.",
                "defeat_text": "Sophie: Terrifying in a very losable way, apparently.",
                "reward": 1700,
            },
            {
                "name": "Blake",
                "class": "Ace Trainer",
                "team": [("Dratini", 26), ("Aqualet", 26), ("Tatsugiri", 27)],
                "greeting": "Blake: You've made it through four routes to reach me. Slateport is just ahead — but only if you get past me first.",
                "defeat_text": "Blake: You've earned it. Coral's waiting.",
                "reward": 1900,
            },
        ],
    },

    "Route 13": {
        "description": "A long road climbing out of the coastal lowlands. The air gets drier the further north you go.",
        "wild_pokemon": [
            {"name": "Axew",     "min_level": 28, "max_level": 31, "rate": 30},
            {"name": "Sandile",  "min_level": 28, "max_level": 30, "rate": 25},
            {"name": "Druddigon","min_level": 29, "max_level": 31, "rate": 25},
            {"name": "Pawniard", "min_level": 28, "max_level": 30, "rate": 20},
        ],
        "trainers": [
            {
                "name": "Dan",
                "class": "Young Trainer",
                "team": [("Axew", 29), ("Sandile", 28)],
                "greeting": "Dan: Left Slateport two days ago. Haven't lost a battle yet.",
                "defeat_text": "Dan: Make that two days and one loss.",
                "reward": 1950,
            },
            {
                "name": "Fiona",
                "class": "Young Trainer",
                "team": [("Pawniard", 29), ("Druddigon", 30)],
                "greeting": "Fiona: Steel and Dragon. Try cutting through that.",
                "defeat_text": "Fiona: You found a way through. Impressive.",
                "reward": 2000,
            },
            {
                "name": "Chris",
                "class": "Young Trainer",
                "team": [("Axew", 30), ("Pawniard", 29), ("Sandile", 30)],
                "greeting": "Chris: I've been training on this route for a week straight. You're in for it.",
                "defeat_text": "Chris: A week of training and still not enough. Back to it.",
                "reward": 2100,
            },
        ],
    },

    "Route 14": {
        "description": "Rocky highland scrubland. Evolved Pokémon patrol the high ground.",
        "wild_pokemon": [
            {"name": "Fraxure",  "min_level": 30, "max_level": 33, "rate": 25},
            {"name": "Krokorok", "min_level": 30, "max_level": 32, "rate": 25},
            {"name": "Druddigon","min_level": 30, "max_level": 33, "rate": 25},
            {"name": "Bisharp",  "min_level": 30, "max_level": 32, "rate": 25},
        ],
        "trainers": [
            {
                "name": "Leo",
                "class": "Young Trainer",
                "team": [("Fraxure", 31), ("Krokorok", 30)],
                "greeting": "Leo: Fraxure can crack boulders with one swing. You're softer than a boulder.",
                "defeat_text": "Leo: Apparently not softer. My mistake.",
                "reward": 2050,
            },
            {
                "name": "Iris",
                "class": "Young Trainer",
                "team": [("Bisharp", 31), ("Druddigon", 32)],
                "greeting": "Iris: These highlands belong to the strong. Prove you belong here.",
                "defeat_text": "Iris: You belong here. I'll accept that.",
                "reward": 2100,
            },
            {
                "name": "Marcus",
                "class": "Young Trainer",
                "team": [("Fraxure", 32), ("Bisharp", 31), ("Krokorok", 32)],
                "greeting": "Marcus: Three fully evolved lines by Route 14. I've put in the work.",
                "defeat_text": "Marcus: You put in more. Noted.",
                "reward": 2200,
            },
        ],
    },

    "Route 15": {
        "description": "The final approach to Jubilife City. The skyline is already visible on the horizon.",
        "wild_pokemon": [
            {"name": "Fraxure",  "min_level": 32, "max_level": 34, "rate": 25},
            {"name": "Dragonair","min_level": 31, "max_level": 34, "rate": 20},
            {"name": "Larvitar", "min_level": 31, "max_level": 34, "rate": 25},
            {"name": "Druddigon","min_level": 32, "max_level": 35, "rate": 20},
            {"name": "Bisharp",  "min_level": 32, "max_level": 34, "rate": 10},
        ],
        "trainers": [
            {
                "name": "Ben",
                "class": "Young Trainer",
                "team": [("Dragonair", 32), ("Larvitar", 31)],
                "greeting": "Ben: Dragonair evolved last night. I haven't stopped smiling since.",
                "defeat_text": "Ben: Still smiling. Just less.",
                "reward": 2150,
            },
            {
                "name": "Lucy",
                "class": "Young Trainer",
                "team": [("Fraxure", 33), ("Druddigon", 33)],
                "greeting": "Lucy: Jubilife's right there. One last fight before the city.",
                "defeat_text": "Lucy: Good warmup for whoever you face in there.",
                "reward": 2200,
            },
            {
                "name": "Adrian",
                "class": "Ace Trainer",
                "team": [("Dragonair", 34), ("Fraxure", 33), ("Druddigon", 35)],
                "greeting": "Adrian: Jubilife has seen war. The trainers who walk through its gates should be ready for anything.",
                "defeat_text": "Adrian: You're ready. Walk through.",
                "reward": 2500,
            },
        ],
    },
}

